origin_experiment_name: yaml #["input", "yaml"]
experiment_name: "epochs_5000_temporal"
random_state: 42
snapshots:
  file_type_str: 'numpy' #h5_libmesh
  folder: 'data/input'
  visualization_folder: 'data/visualization'
  file_name_contains: ['snapshots']
  dataset: null
splitting:
  splitting_strategy: "temporal" #["temporal", "kfold", "train_test", train_val]
  splitting_strategy_parameters:
    active: True
    parameters: 
      n_splits: 3
normalization:
  snapshots: null
  svd: null
  auto_encoder: "min_max"
  surrogate: null
svd:
  trunc_basis: 270
  svd_type: "randomized_svd"  # ["full_svd", "randomized_svd"]
  power_iterations: 1
  oversampling: 20
auto_encoder:
  data_loader: "data_loader"
  data_loader_parameters:
    active: True
    parameters:
      batch_size: 64
      num_workers: 4
  num_epochs: 5000
  initializer: "kaiming_normal"
  initializer_parameters:
    active: True
    parameters:
      mode: "fan_in"
      nonlinearity: "leaky_relu"
  optimizer: "adam"
  optimizer_parameters:
    active: True
    parameters:
      lr: 0.0001
      weight_decay: 0.00000001
  loss_function: "smooth_l1_loss"
  loss_function_parameters:
    active: True 
    parameters:
      beta: 0.2
  number_of_hidden_layers: 5
  hidden_layers_sizes: 
    0: 256
    1: 128
    2: 64
    3: 32
    4: 16
  hidden_layers_activation_function:
    0: "leaky_relu"
    1: "leaky_relu"
    2: "leaky_relu"
    3: "leaky_relu"
  hidden_layers_activation_function_parameters:
    active: 
      0 : True
      1 : True
      2 : True
      3 : True
    parameters:
      0 : 
        negative_slope : 0.2
      1 : 
        negative_slope : 0.2
      2 : 
        negative_slope : 0.2
      3 : 
        negative_slope : 0.2 
  decoder_activation_function: 
      0: "sigmoid"
  decoder_activation_function_parameters: 
    active: 
      0: False
    parameters:
      0: null
